[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hashreport"
version = "0.1.0"
dependencies = [
    "pytablewriter",
]

[project.scripts]
hashreport = "hashreport:main"
